# Generated by Django 6.0.3 on 2026-05-02 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True, verbose_name='Antécédents médicaux'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_treatments',
            field=models.TextField(blank=True, verbose_name='Traitements en cours'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='past_surgeries',
            field=models.TextField(blank=True, verbose_name='Antécédents chirurgicaux'),
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('prescription', 'Ordonnance'), ('lab_result', "Résultat d'analyse"), ('report', 'Compte rendu médical'), ('imaging', 'Imagerie'), ('other', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True, verbose_name='Pression systolique')),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True, verbose_name='Pression diastolique')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Fréquence cardiaque')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Taille (cm)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
